services:
  - type: web
    name: hr-management
    env: python
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn hr_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: hr-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: hr_project.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: hr-db
    databaseName: hr_db
    user: hr_user 