# Generated by Django 5.0.2 on 2025-06-18 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_callresponse_recording_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='callresponse',
            name='call_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callresponse',
            name='call_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callresponse',
            name='call_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='callresponse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='callresponse',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callresponse',
            name='recording_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callresponse',
            name='recording_sid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
